export * from './BoostIcon';
export * from './CoronaIcon';
export * from './DialIcon';
export * from './IncreaseIcon';
export * from './ScercyLogo';
export * from './TargetIcon';
export * from './StarIcon';
export * from './ArrowIcon';
export * from './PlayIcon';
